### ISSUE TITLE
Outdated guide

### ISSUE THREAD

**Issue by Andre601** [ThatTonybo/Revolt-Discord-Theme#16]
It seems like that this guide is a bit outdated, as there doesn't seem to be any "Import theme" button anymore in the advanced options for the appearance settings.
The only thing left there are the font choice and a CSS box.

So the guide should be updated to reflect this change.

**Comment by Snazzah** [comment]
It's actually in "Theme Overrides" lol
![](https://get.snaz.in/3ynWjJc.png)

**Comment by Andre601** [comment]
Oh, right...

But to be fair, the button does look more like a download button for me....

**Comment by Andre601** [comment]
Also, to get back to this, this section is (as shown in your screenshot) called "Theme overrides" while the readme mentions "advanced options", so....

**Comment by Snazzah** [comment]
I'm already updating it: https://github.com/ThatTonybo/Revolt-Discord-Theme/commit/5898767680cd32878b2c50d40f3ae31e639d5cb7
