### ISSUE TITLE
Fix Buttons 

### ISSUE THREAD

**Issue by oumellouk** [ThatTonybo/Revolt-Discord-Theme#7]
as shown on your repo , i dont get the ( Discord-like ) buttons on Windows Client 
screenshot : 
![image](https://user-images.githubusercontent.com/66308295/131565665-8527940b-5420-494f-b8dc-cd93ab744eb2.png)

**Comment by ThatTonybo** [comment]
Read the current disclaimer about the theme being non-functional due to the new update. We are fixing it as fast as we can.
